import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Auth with wallet</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <main>
                <div>
                    <Header />
                </div>
                <div>TEST</div>
            </main>
        </div>
    )
}
